spring.application.name=SmartRecruit

# Configuration de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/smart?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=95759khmiletttH_g
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081

# Configuration Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
